// Generated by Haxe 4.3.6
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var haxe_ds_List = function() { };
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var React_Component = require("react").Component;
var ReactDOM = require("react-dom");
var react_ReactMacro = function() { };
var src_App = function(props,context) {
	React_Component.call(this,props,context);
};
src_App.main = function() {
	ReactDOM.render({ $$typeof : $$tre, type : src_App, props : { }, key : null, ref : null},window.document.getElementById("root"));
};
src_App.__super__ = React_Component;
src_App.prototype = $extend(React_Component.prototype,{
	render: function() {
		var cname = "it-bops";
		return { $$typeof : $$tre, type : "div", props : { className : cname, children : [{ $$typeof : $$tre, type : "h1", props : { children : "Hello React"}, key : null, ref : null},{ $$typeof : $$tre, type : "newItem", props : { }, key : null, ref : null}]}, key : null, ref : null};
	}
	,newItem: function() {
		return { $$typeof : $$tre, type : "input", props : { name : "new item"}, key : null, ref : null};
	}
});
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
src_App.displayName = "App";
src_App.main();
})({});
